apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: APPINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: appinsights-connection
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: azure-tenant-id
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: azure-client-id
            - name: AZURE_SQL_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: azure-sql-url
            - name: SERVICEBUS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: servicebus-enabled
            - name: SERVICEBUS_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: servicebus-queue-name
            - name: SERVICEBUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: servicebus-connection
          {{- with .Values.resources.backend }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: api-frontend
  template:
    metadata:
      labels:
        app: api-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          ports:
            - containerPort: 80
          env:
            - name: APIM_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: apim-base-url
          {{- with .Values.resources.frontend }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
