apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Values.namespace }}
stringData:
  azure-sql-url: {{ .Values.secrets.azureSqlUrl | quote }}
  azure-client-id: {{ .Values.secrets.azureClientId | quote }}
  azure-tenant-id: {{ .Values.secrets.azureTenantId | quote }}
  appinsights-connection: {{ .Values.secrets.appInsightsConnection | quote }}
  azure-client-secret: {{ .Values.secrets.azureClientSecret | quote }}
  servicebus-connection: {{ .Values.secrets.serviceBusConnection | quote }}
