apiVersion: v1
kind: Service
metadata:
  name: api-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api-backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
  type: {{ .Values.service.backend.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-frontend-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api-frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
  type: {{ .Values.service.frontend.type }}
