apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-first-ingress
  namespace: api-first-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - api-first-demo.example.com
      secretName: api-first-demo-tls
  rules:
    - host: api-first-demo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-backend-svc
                port:
                  number: 80
