apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: api-first-demo
stringData:
  azure-sql-url: jdbc:sqlserver://server.database.windows.net:1433;database=db;encrypt=true
  azure-client-id: 00000000-0000-0000-0000-000000000000
  azure-tenant-id: 00000000-0000-0000-0000-000000000000
  appinsights-connection: InstrumentationKey=00000000-0000-0000-0000-000000000000
  azure-client-secret: super-secret-value
  servicebus-connection: Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BASE64==
